### ISSUE TITLE
Rozłączanie po nawiązaniu połączenia na niektórych numerach

### ISSUE THREAD

**Issue by lpiob** [wojtekka/libgadu#19]
Wszystkie aplikacje korzystające z libgadu w najnowszych wersjach nie są w stanie połączyć się z niektórymi numerami GG. Powtarzalne za każdym razem, testowane w kilku różnych środowiskach Linux 64bit z wykorzystaniem libgadu kompilowanego samodzielnie i paczkowanego (Debian, Ubuntu, PPA).

Posiadam dwa, ośmiocyfrowe numery GG. Na jednym z nich po połączeniu jestem automatycznie rozłączany z serwerem, jeśli korzystam z nowszych wersji biblioteki libgadu. Tuż przed rozłączaniem pokazywana jest lista kontaktów i statusów dostępności osób na niej. Drugi numer działa bez zarzutu.

Zrzut z okienka debugu ekg2, widać na nim pobieranie kontaktów oraz moment rozłączenia z soczystym komunikatem (otrzymanym od serwera gg?): http://pastebin.ca/3413415

Problem dotyczy zarówno biblioteki kompilowanej ręcznie, jak i dostępnej w repozytoriach Debiana i Ubuntu. Od pewnej wersji, na tym jednym numerze po prostu nie można się połączyć. Klient nie ma znaczenia - to samo dzieje się na ekg2 jak i na kadu.

**Comment by lpiob** [comment]
Za pomocą bisecta zidentyfikowałem commity:
4d642839e0ed54de9f8fab6a31e66094e8722f8a jako ostatni dobry
d7ab589b063abf87da61bff840f8263f5bacce06 jako pierwszy wadliwy, ale nie kompilujący się commit
7995ca0bc77ca53e4f1da75afd5b5b6fede594af pierwszy ktory sie kompiluje i nie pozwala na połączenie.

**Comment by twasilczyk** [comment]
Problemem jest niewłaściwa implementacja gg_session_handle_chat_info. Nie potrafi sparsować pakietu i się wysypuje. Log, który przesłałeś powinien wystarczyć do naprawienia problemu, ale jeżeli jest taka możliwość, to nie loguj się proszę na ten numer z innego komunikatora, żebyśmy mogli potwierdzić rozwiązanie po napisaniu łatki.

Problem występuje tylko na numerach, które są dodane do czatu wieloosobowego (być może nie na wszystkich).

**Comment by twasilczyk** [comment]
4955fbe naprawia ten problem. Proszę o potwierdzenie.

**Comment by lpiob** [comment]
Potwierdzam, że wszystko działa, dziękuje.
