### ISSUE TITLE
Error building libgadu with clang

### ISSUE THREAD

**Issue by slacka** [wojtekka/libgadu#22]
When trying to build libgadu with clang, I get:

`handlers.c:1434:6: error: absolute value function 'abs' given an argument of type 'long' but has parameter of type 'int' which may cause truncation of value`

The log of this can be found here:
http://clang.debian.net/logs/2016-08-30/libgadu_1.12.1-2_unstable_clang.log

**Comment by twasilczyk** [comment]
It's fixed in d56670d. I feel it's time for a release.
