### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by mpapierski** [wojtekka/libgadu#23]
I'm playing with `libgadu` by trying to develop bindings for various new language ([node-gadu], [go-gadu]). This is a good exercise to learn new technology.

While working on Go bindings I realised that error reporting in `libgadu` could be improved. This library in most calls sets `errno` and returns `-1` - which is fine in most cases. For example, in Go accessing `errno` isn't easy because you'll never know which thread will gets the value of it. And its not just go -- actually it feels like the library tries to fit error states into `errno(3)` constants.

Simplest thing we can do about it is to return (for example) `-EFAULT` instead `-1` (AFAIK `libuv` does this for the same reason).

The other idea I've got is to create an enum with errors such as

```c
enum {
  GG_OK = 0,
  GG_ERROR_ACCESS_DENIED
}
``` 
and return those values instead of setting `errno`. And add functions such as `gg_errstr`. This would break literally every application.

If there is any interest I'd love to try with implementation! 

[node-gadu]: https://github.com/mpapierski/node-gadu
[go-gadu]: https://github.com/mpapierski/go-gadu

**Comment by twasilczyk** [comment]
I'm afraid we can't change this behaviour without bumping major API version and we don't plan releasing libgadu 2.0.0.

On Linux (and apparently on MSVC) errno is thread-local, so it always gets set for the same thread that called libgadu function.

However, while libgadu is thread-safe, it's not meant to be multithreaded - you should have a dedicated thread to interact with the library.
