### ISSUE TITLE
English description

### ISSUE THREAD

**Issue by ghost** [wojtekka/libgadu#27]
Hi there,

Could you perhaps add a short english subsection to the main readme? Just to detail what the library does. I understand that you probably do not target english-speaking people, but for the english-speaking people it may be interesting to know what the code does.

Thank you!

**Comment by RobFog** [comment]
Indeed!

**Comment by wojtekka** [comment]
[English README](https://github.com/wojtekka/libgadu/blob/master/README.en) was added and an [English version of the website](http://libgadu.net/index.en.html) as well.
